[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/success"
  to = "/"
  status = 200

[context.production]
  command = "npm run build"
  publish = "build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex"
