[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/success"
  to = "/"
  status = 200

# Налаштування для production (stoautovibe.com.ua) — індексація дозволена, без noindex
[context.production]
  command = "npm run build"
  publish = "build"
  [[headers]]
    for = "/*"
    [headers.values]
      # не ставимо X-Robots-Tag — індексація дозволена

# Для інших контекстів (preview, netlify.app) — заборона індексації
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex"
